### ISSUE TITLE
ImportError: cannot import name 'validate_cot_steps' from 'pocketgroq.chain_of_thought.utils' 

### ISSUE THREAD

**Issue by solo2424** [jgravelle/GroqCasters#5]
I am trying to run this on a windows PC and I am geting this error. I tried uninstalling and reinstalling but I still get this.  

(venv) (base) PS C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters> python groqcasters.py c:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\GroqCasters\input\input.txt c:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\GroqCasters\output
Traceback (most recent call last):
  File "C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters\groqcasters.py", line 5, in <module>
    from pocketgroq import GroqProvider, GroqAPIKeyMissingError, GroqAPIError
  File "C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters\venv\Lib\site-packages\pocketgroq\__init__.py", line 3, in <module>
    from .groq_provider import GroqProvider
  File "C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters\venv\Lib\site-packages\pocketgroq\groq_provider.py", line 19, in <module>
    from .chain_of_thought.cot_manager import ChainOfThoughtManager
  File "C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters\venv\Lib\site-packages\pocketgroq\chain_of_thought\__init__.py", line 5, in <module>        
    from .utils import sanitize_input, validate_cot_steps
ImportError: cannot import name 'validate_cot_steps' from 'pocketgroq.chain_of_thought.utils' (C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters\venv\Lib\site-packages\pocketgroq\chain_of_thought\utils.py)
(venv) (base) PS C:\Users\jerem\Sandbox\Web_App_Projects\GroqCaster\groqcasters>

**Comment by jgravelle** [comment]
You'll probably need the pocketgroq 0.4.7 upgrade, as soon as I get it
pooshed...


-jjg

**Comment by jgravelle** [comment]
0.4.8 available...
